# Generated by Django 3.0.8 on 2020-07-26 01:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentence', models.CharField(max_length=128)),
                ('is_grammatical', models.BooleanField()),
                ('sentence_type', models.CharField(choices=[('FL', 'Filler'), ('RL', 'Real')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=1)),
                ('academic_background', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judgement_result', models.BooleanField()),
                ('judgement_reaction_time', models.FloatField()),
                ('reaction_time', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('reaction_time_absolute', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('order', models.IntegerField()),
                ('stimlus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Stimulus')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Subject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trial',
            constraint=models.UniqueConstraint(fields=('order', 'subject'), name='experiment-order'),
        ),
    ]
