# Generated by Django 3.0.8 on 2020-07-28 13:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentence', models.CharField(max_length=128)),
                ('is_grammatical', models.BooleanField()),
                ('type', models.CharField(choices=[('filler', 'Filler'), ('direct', 'Direct'), ('indirect', 'Indirect')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('birthdate', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=1)),
                ('academic_background', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foreign_experience', models.CharField(choices=[('no', '없음'), ('less_1year', '1년 미만'), ('more_1year', '1년 이상')], max_length=128)),
                ('foreign_experience_country', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judgement_result', models.BooleanField()),
                ('judgement_reaction_time', models.FloatField()),
                ('reaction_time', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('reaction_time_absolute', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('order', models.IntegerField()),
                ('exp_date', models.DateField(auto_now_add=True)),
                ('stimulus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.Stimulus')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.Subject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trial',
            constraint=models.UniqueConstraint(fields=('order', 'subject'), name='experiment-order'),
        ),
    ]
