# Generated by Django 3.0.8 on 2020-07-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trial',
            name='experiment-order',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='subject',
            new_name='session_id',
        ),
        migrations.AddConstraint(
            model_name='trial',
            constraint=models.UniqueConstraint(fields=('order', 'session_id'), name='experiment-order'),
        ),
    ]
