# Generated by Django 3.0.8 on 2020-07-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20200729_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
