# Generated by Django 3.0.8 on 2020-07-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20200727_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stimulus',
            name='sentence_type',
        ),
        migrations.AddField(
            model_name='stimulus',
            name='type',
            field=models.CharField(choices=[('FL', 'Filler'), ('DI', 'Direct'), ('IN', 'Indirect')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
