# Generated by Django 3.0.8 on 2020-08-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_subject_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='corsi_span',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
