# Generated by Django 3.0.8 on 2020-07-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20200728_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulus',
            name='type',
            field=models.CharField(choices=[('filler', 'Filler'), ('direct', 'Direct'), ('indirect', 'Indirect')], max_length=10),
        ),
    ]
