# Generated by Django 3.0.8 on 2020-07-28 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20200728_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulus',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='stimlus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.Stimulus'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.Subject'),
        ),
    ]
