# Generated by Django 3.0.8 on 2020-08-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_subject_corsi_span'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='foreign_experience',
        ),
        migrations.AddField(
            model_name='subject',
            name='foreign_experience_duration',
            field=models.CharField(choices=[('no', '없음'), ('2-', '2년 미만'), ('2+', '2년 이상'), ('3+', '3년 이상')], default='no', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='foriegn_experience_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
