# Generated by Django 3.0.8 on 2020-07-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_remove_stimulus_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='stimlus',
            new_name='stimulus',
        ),
        migrations.AddField(
            model_name='trial',
            name='exp_date',
            field=models.DateField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
