# Generated by Django 3.0.8 on 2020-08-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20200825_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulus',
            name='group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=10),
            preserve_default=False,
        ),
    ]
