# Generated by Django 3.0.8 on 2020-08-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_subject_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulus',
            name='event',
            field=models.IntegerField(default=-1),
        ),
    ]
