# Generated by Django 3.0.8 on 2020-08-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_stimulus_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='foreign_experience_age',
            field=models.IntegerField(default=-1),
        ),
    ]
