# Generated by Django 3.0.8 on 2020-08-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20200826_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
